"""
 plotVisibility.py
   plotVisibility (filename)

 Open satellite visibility log file (.txt) generated by bladeGPS and plot it.

 Shingo Nishimoto, 2024.

      Args:
        filename: path to file

      Return:

 -----------------------------------------------------------------------------

 GNSS-SDR is a Global Navigation Satellite System software-defined receiver.
 This file is part of GNSS-SDR.

 Copyright (C) 2022  (see AUTHORS file for a list of contributors)
 SPDX-License-Identifier: GPL-3.0-or-later

 -----------------------------------------------------------------------------
"""
import os

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from scipy import interpolate


def plotVisibility(filename: str, path: str) -> np.array:

    # ---------- CHANGE HERE:
    fig_path = path + 'figure/'

    if not os.path.exists(fig_path):
        os.makedirs(fig_path)

    df = pd.read_csv(filename)
    # print(df.head())
    num_of_visible_sats = df.drop('t', axis=1).sum(axis=1)

    # FIXME: add more variety plots.
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.set_ylim(0, 20)
    plt.gca().yaxis.set_major_locator(mticker.MultipleLocator(2))
    ax.set_xlabel("Rx Time [s]")
    ax.set_ylabel("# of visible sats")
    ax.grid(axis='y')
    ax.plot(df["t"], num_of_visible_sats)

    plt.savefig(os.path.join(fig_path, 'num_of_visible_sats.png'))
    plt.show()
